# Umbrales de elegibilidad
MIN_CLICKS_FOR_ANALYSIS = 100
MIN_INVESTMENT_SHARE = 0.01
MIN_ACTIVE_DAYS = 7


# Umbrales de variación
CTR_VARIATION_THRESHOLD = 0.25
CPC_VARIATION_THRESHOLD = 0.25
CPA_VARIATION_THRESHOLD = 0.30


# Umbrales de outliers
OUTLIER_ZSCORE_THRESHOLD = 2.0